version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - Setting up environment variables and other setup ...
      - export FLASK_ENV=test

  build:
    commands:
      - echo Running tests...
      - pytest tests/ --junitxml=reports/test-report.xml

  post_build:
    commands:
      - echo Build complete
      - echo Tests finished
artifacts:
  files:
    - '**/*'